
INSERT INTO products (name, description, price, image_url, category, subcategory, is_active) VALUES 
('Sunset Crop Tee', 'Soft cotton crop tee in warm sunset hues. Perfect for layering or wearing solo. Relaxed fit with a flattering cropped silhouette.', 2800, 'https://mocha-cdn.com/0199e222-1be9-72bc-aa82-20c4d89a63a8/product-croptee-1.jpg', 'Tops', 'Crop Tops', 1),
('Cloud Oversized Hoodie', 'Ultra-soft fleece hoodie in cloud white. Oversized fit with kangaroo pocket and adjustable drawstring hood. Perfect for cozy days.', 6800, 'https://mocha-cdn.com/0199e222-1be9-72bc-aa82-20c4d89a63a8/urban-hoodie-cream.jpg', 'Outerwear', 'Hoodies', 1),
('Vintage High-Rise Jeans', 'Classic high-waisted jeans in light vintage wash. Comfortable stretch denim with authentic fading. Timeless silhouette that flatters every body.', 8900, 'https://mocha-cdn.com/0199e222-1be9-72bc-aa82-20c4d89a63a8/urban-jeans-light.jpg', 'Bottoms', 'Jeans', 1),
('Blush Oversized Blazer', 'Structured blazer in soft blush pink. Oversized fit with padded shoulders and functional pockets. Perfect for both casual and formal looks.', 12800, 'https://mocha-cdn.com/0199e222-1be9-72bc-aa82-20c4d89a63a8/urban-blazer-pink.jpg', 'Outerwear', 'Blazers', 1),
('Flow Midi Dress', 'Elegant flowing midi dress in soft peach. Lightweight fabric with subtle texture. Features adjustable straps and flattering A-line silhouette.', 9800, 'https://mocha-cdn.com/0199e222-1be9-72bc-aa82-20c4d89a63a8/urban-dress-peach.jpg', 'Dresses & Jumpsuits', 'Midi Dresses', 1),
('Cream Knit Cardigan', 'Cozy knit cardigan in cream white. Soft wool blend with button closure and relaxed fit. Perfect for layering in any season.', 7800, 'https://mocha-cdn.com/0199e222-1be9-72bc-aa82-20c4d89a63a8/urban-cardigan-cream.jpg', 'Outerwear', 'Cardigans', 1),
('Essential Crop Top', 'Basic crop top in soft beige. Ribbed cotton fabric with fitted silhouette. Perfect foundation piece for any wardrobe.', 3200, 'https://mocha-cdn.com/0199e222-1be9-72bc-aa82-20c4d89a63a8/urban-croptop-beige.jpg', 'Tops', 'Crop Tops', 1),
('Linen Button Shirt', 'Relaxed linen shirt in soft pink. Breathable fabric with classic collar and button closure. Perfect for warm weather styling.', 6200, 'https://mocha-cdn.com/0199e222-1be9-72bc-aa82-20c4d89a63a8/product-shirt-1.jpg', 'Tops', 'Shirts', 1),
('Cozy Knit Sweater', 'Chunky knit sweater in cream. Soft wool blend with relaxed fit and ribbed trim. Perfect for cooler days and cozy moments.', 8800, 'https://mocha-cdn.com/0199e222-1be9-72bc-aa82-20c4d89a63a8/product-sweater-1.jpg', 'Tops', 'Sweaters', 1),
('Flowing Wrap Dress', 'Elegant wrap dress with subtle pattern. Lightweight fabric with tie waist and flattering silhouette. Perfect for day to evening wear.', 10800, 'https://mocha-cdn.com/0199e222-1be9-72bc-aa82-20c4d89a63a8/product-wrapdress-1.jpg', 'Dresses & Jumpsuits', 'Casual Dresses', 1);
